version: '3.8'
services:

  db:
    image: mysql
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

  # redis
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_ROOT_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      FROM_EMAIL: ${FROM_EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      CLIENT_ID: ${CLIENT_ID}
      KAKAO_INIT: ${KAKAO_INIT}
      REDIRECT_URI: ${REDIRECT_URI}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - db
      - redis
    ports:
      - "8888:8888"
    networks:
      - app-network

  # nginx
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 이 줄을 추가

networks:
  app-network:
    driver: bridge